#!/bin/bash

appname="iic-scanner"
( git clone https://github.com/Tearran/iic-scanner.git "$HOME/build/main/" )
( cd "$HOME/build/main/" && wget https://raw.githubusercontent.com/Tearran/smbus2/master/smbus2/smbus2.py )
( rm -r "$HOME/build/main/.git/" )
( cd "$HOME/build/main/" && wget "https://raw.githubusercontent.com/Tearran/python-i2c-scanner/master/i2c-scanner.py" )
( mv "$HOME/build/main/i2c-scanner.py" "$HOME/build/main/__main__.py" )
( cd "$HOME/build/main/" && zip "../app.zip" * )
( echo '#!/usr/bin/env python3' | cat - "$HOME/build/app.zip" > "$HOME/build/$appname" )
( chmod +x "$HOME/build/$appname" && sudo cp "$HOME/build/$appname" "/usr/bin/" )
